name : Deploy Place My Order DynamoDb Library

on:
  push:
    branches: ["master"]

env:
  NUGET_TOKEN: ${{ secrets.NUGETACCESSTOKEN }}
permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read
    
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./build
    name: Build and Deploy Job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Execute build and generate nupkg file
        run: |
          ./build.ps1   